config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  #   resources :meme_creator_listing do
  #   # resources :bookings, except: [:index, :show, :update, :edit]
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get '/my_meme_creator_listings', to: 'meme_creator_listings#index'
  # get '/my_bookings', to: 'bookings#index'
  resources :meme_creator_listings, only: [:index, :show, :create] do
  resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :meme_creator_listing
  # validates :user_id, :meme_creator_listings_id, presence: true
end

app/models/meme_creator_listing.rb
class MemeCreatorListing < ApplicationRecord
  belongs_to :user
  # has_many :bookings
  has_one_attached :photo

  validates :description, length: { maximum: 400 }
  # validates :speciality, :hourly_price, :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # has_many :meme_creator_listings
  # has_many :bookings
  # has_one_attached :photo

  validates :name, :email, presence: true
  validates :email, confirmation: true, uniqueness: true
  validates :name, length: { maximum: 16 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :location, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :location, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :find_booking, only: %i[show]

  def index
    @bookings = Booking.where(user: current_user)
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @meme_creator_listing = MemeCreatorListing.find(params[:meme_creator_listing_id])
     @booking = Booking.new

  end

  def create
    @booking = Booking.new(booking_params)
    @booking.meme_creator_listing = MemeCreatorListing.find(params[:meme_creator_listing_id])
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path, notice: "Booking Successful"
    else
      render meme_creator_listings/show
    end
  end

  private

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:meme_creator_listing_id)
  end

end

app/controllers/meme_creator_listings_controller.rb
class MemeCreatorListingsController < ApplicationController
  before_action :find_meme_creator_listing, only: [:show]

  def index
    @meme_creator_listings = MemeCreatorListing.all
  end

  def new
    @meme_creator_listing = MemeCreatorListing.new

  end

  def create
    @meme_creator_listing = MemeCreatorListing.new(meme_creator_listing_params)
  end



  def show
    @meme_creator_listing = MemeCreatorListing.find(params[:id])
    @booking = Booking.new
  end


  private

  def meme_creator_listing_params
    params.require(:list).permit(:creator_name, :speciality, :hourly_price, :photo)
  end

  def find_meme_creator_listing
    @meme_creator_listing = MemeCreatorListing.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<header class=" bg-bg-3 text-center">
		<div class="container">
			<h2 class="display-3 mb-4 mb-xl-6" data-aos="fade-down" data-aos-delay="0">
				Your Bookings
			</h2>
			<p class="fs-1 remove-br" data-aos="fade-down" >
				These creators are booked to make some meme &#x1f525; for you
			</p>
		</div>
	</header>
	<!-- Team 2 -->
		<section class=" text-center">

      <%# <% @bookings.each do |booking|%>
			<%# <div class="container">
				<div class="row justify-content-center">
					<div class="col-sm-6 col-md-5 col-lg-3 mb-6 mb-lg-0" data-aos="fade-down" data-aos-delay="400">
						<div class="border rounded-2 border-dark-3 p-6 h-100 shadow">
							<% cl_image_tag booking.meme_creator_listing.photo.key, class:"img-fluid mb-6 rounded-1" %>
							<%# <h5 class="mb-2">
    	          <%# <%= booking.meme_creator_listing.creator_name %>
							<%# </h5>
							<p class="mb-4">
								<%= booking.meme_creator_listing.speciality %>
							<%# </p>
						</div> %>
					<%# </div>
         <%end %>

<section class=" text-center">
			<div class="container">
				<div class="py-10 row justify-content-center">
					<div class="py-5 col-sm-6 col-md-5 col-lg-3 mb-6 " data-aos="fade-down" >
						<div class="border rounded-2 border-dark-3 p-6 h-100 shadow">
							<img src='https://res.cloudinary.com/dza6mn30y/image/upload/v1644368310/memes/eggcellent_hugip3.jpg' srcset="i/team-2-2@2x.jpg 2x" alt="" class="img-fluid rounded-1">
							<h5 class="mb-2">
  Eggmeister
							</h5>
							<p class="mb-4">
								Egg Meme specialist
							</p>
						</div>
					</div>

<br><br>
<br><br>
<br><br>
<br><br>
				</div>
			</div>
		</section>

app/views/bookings/new.html.erb
<h1 class="text-center">Book a Meme Creator</h1>

<div class="container center_div" style="width: 500px">
  <%= simple_form_for [ @meme_creator_listing, @booking ] do |f| %>
    <div class="p-3">
      <%= f.label :date_booked, "Booking Date:" %>
      <%= f.date_field :date_booked, as: :date, value: f.object.try(:strftime,"%d/%m/%Y"), class: 'form-control' %>
    </div>
       <div class="p-3">
      <%= f.submit "Book this Meme Creator!", class: "btn btn-primary" %>
    </div>
<% end %>
</div>

app/views/bookings/show.html.erb
<h1>Booking</h1>
<br><br>
<div class="booking-show-container">
  <% Date = @booking.date_booked %>
  <h3>Confirmed:<%= @booking.meme_creator_listing %></h3>
  <div class="booking-show-status">
    <p>Booked by <%= @booking.user.name %><%= @booking.created_at.strftime(" on %m/%d/%Y") %></p>
     <% end %>
  </div>
</div>

<section class="bg-bg-3 py-4 py-lg-8 text-center">
		<div class="container">
			<img src="i/blog-16.jpg" srcset="i/blog-16@2x.jpg 2x" alt="" class="img-fluid rounded-circle mb-2" data-aos="fade-down" data-aos-delay="0">
			<h5 class="mb-1 pt-xxl-4" data-aos="fade-down" data-aos-delay="250">
				PROGRAMMERS MEME CREATOR
			</h5>
			<p class="mb-0 pb-xxl-12" data-aos="fade-down" data-aos-delay="500">
				£20
			</p>
			<a href="#" class="btn btn-dark-1 position-relative">
				CHECKOUT
			</a>
		</div>
	</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemesForYears</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bubblegum+Sans&display=swap" rel="stylesheet">
     <link href="https://fonts.googleapis.com/css2?family=Bubblegum+Sans&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
        <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/meme_creator_listings/_bookings_form.html.erb
<div class="container center_div" style="width: 500px">
  <%= simple_form_for [ @meme_creator_listing, @booking ] do |f| %>
    <div class="p-3">
      <%# <%= f.label :date_booked, "Booking Date:" %>
      <%# # <%= f.date_field :date_booked, as: :date, value: f.object.try(:strftime,"%d/%m/%Y"), class: 'form-control' %>
    </div>
       <div class="p-3">
      <%= f.submit "Book this Meme Creator!", class: "btn btn-primary" %>
    </div>
<% end %>
</div>

app/views/meme_creator_listings/index.html.erb
<div class="container">
			<div class="row justify-content-between align-items-center mb-15">
				<div class="col-md-9 col-lg-7 col-xl-6 col-xxl-5">
					<h2 class="display-5 mb-4 mb-lg-0" data-aos="fade-down" data-aos-delay="0">
								Check Out Our Resident Meme Specialists
					</h2>
				</div>
				<div class="col-md-9 col-lg-5">
					<p class="fs-2 mb-0 w-75" data-aos="fade-down" data-aos-delay="150">
								These guys know how to create pointless memes that go viral &#x1f680;
					</p>
				</div>


			</div>
			<div class="row" data-aos="fade-down" data-aos-delay="250">
       <% @meme_creator_listings.each do |creator|%>
				<div class="mb-6 col-lg-4 col-md-6">
					<a href="#" class="d-block rounded-0 h-75 mb-4">
						<%= cl_image_tag creator.photo.key,  class: "mb-4 rounded-2 shadow d-xxl-flex w-100 h-100 position-relative img-fluid" %>
					</a>
					 <%= link_to "View More", meme_creator_listing_path(creator), class:"btn float-xxl-end btn-outline-dark-2 btn-sm pt-2 mt-3" %>

					</a>
					<div class="row justify-content-between">
						<div class="col">
						</div>
					</div>
					<h5>
						<%= creator.creator_name %>
					</h5>
					<h6 class="fw-1">
							<%= creator.speciality %>
					</h6>
				</div>
<% end %>

				</div>
			</div>
		</div>

app/views/meme_creator_listings/show.html.erb
<section class="py-10 py-lg-20 bg-bg-3 text-center">
		<div class="container col-auto">
			<div class="justify-content-center row">
				<div class="col-md-9 col-lg-7 col-xl-6 col-xxl-5">
					<h2 class="display-5 mb-0 float-xxl-none" data-aos="fade-down" data-aos-delay="0">
							<%= @meme_creator_listing.creator_name %>
					</h2>
					<p class="mb-15 fs-2 py-0" data-aos="fade-down" data-aos-delay="150">
							<%= @meme_creator_listing.speciality %>
					</p>
				</div>
			</div>
			<div class="row">
				<div class="mb-3 mb-sm-6 col-lg-6 container-xl" data-aos="fade-down" data-aos-delay="400">
					<a href="#" class="d-block rounded-1">
						<%= cl_image_tag @meme_creator_listing.photo.key, class: "w-100 rounded-1 shadow" %>
					</a>
				</div>
			</div>
			<div class="row">
				<div class="mb-3 mb-sm-6 col-lg-6 container-xl" data-aos="fade-down" data-aos-delay="400">
					<p class="fs-2 fw-bold float-xxl-start">
								Price per Meme : £20
					</p>
				</div>
			</div>
			<div class="row">
				<div class="mb-3 mb-sm-6 col-lg-6 container-xl position-relative" data-aos="fade-down" data-aos-delay="400">


          <%#= render "bookings_form" %>
          <%= link_to "Book", bookings_path, class: "btn shadow rounded" %>

				</div>
			</div>
		</div>
	</section>

app/views/pages/home.html.erb
<div class="container pb-5">
<h1 class="text-center font-sans subpixel-antialiased font-extrabold black"></h1>
<div class= "home-padding">

</div>
<div class=" flex flex-col my-auto items-center ">
    <img class="mx-auto d-block" src="https://res.cloudinary.com/dza6mn30y/image/upload/c_scale,h_450/v1644283210/Full_Logo_lvetia.png" alt="Workflow logo">
</div>

<h3 class ="text-center font-sans subpixel-antialiased"> Go viral on social 🙌 - Book the best meme creators in the world!</h3>

<%= simple_form_for :search, url: root_path, method: :get do |f| %>

    <div class="search-form-control form-group col-6 mx-auto mt-5">
      <input class="form-control string required" type="text" name="search[query]" id="search_query" />
      <button name="button" type="submit" class="btn btn-flat">
        <i class="fas fa-search"></i> Search
      </button>
    </div>


<% end %>

</div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-tiktok"></i></a>
  </div>
  <div class="footer-copyright">
    © Memes For Days Inc 2022
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "Logo Icon.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
           <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Meme Creators", meme_creator_listings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, :method => :delete, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "Dave.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" id="dropdown-menu-position" style="left:-100px" aria-labelledby="navbarDropdown">
              <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>